name: Deploy to GitHub Pages

on:
  # Triggers the workflow on push or pull request to the main branch
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # or whichever version you're using

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project (creates the dist/ folder)
      - name: Build project
        run: npm run build

      # Step 5: Deploy the `dist/` folder to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist